version: '3.9'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/newsApp/staticfiles
      - media_volume:/newsApp/media
    ports:
      - 8000:80

    depends_on:
      - web

  web:
    build: .
    command:  bash -c "python manage.py migrate --no-input && python manage.py collectstatic --no-input
      && gunicorn project.wsgi:application --bind 0.0.0.0:8001"
    volumes:
      - static_volume:/newsApp/staticfiles
      - media_volume:/newsApp/media
    ports:
      - 8001:8001
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=_2w320i^ibjrkgbfft56h)%r_3$o-b!y2spj0#tygrae*rs!#1
      - DJANGO_DEBUG=False
      - DATABASE_URL=postgres://user_name:user_password@db:5432/database_name
  db:
    image: postgres:13
    restart: "on-failure"
    environment:
      - POSTGRES_DB=database_name
      - POSTGRES_USER=user_name
      - POSTGRES_PASSWORD=user_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume: